print('Este programa descreve os tipos do input')
v = input('Digite algo: ')
#print('O tipo primitivo desse valor é: ', type(v))
#print('Só tem espaços? ', v.isspace())
#print('É um númerico? ', v.isnumeric())
#print('É alfabético?', v.isalpha())
#print('É alfanumérico? ', v.isalnum())
#print('Está em maiusculas? ', v.isupper())
#print('Está em minusculas? ', v.islower())
#print('Está capitalizada? ', v.capitalize())
a = type(v)
b = v.isspace()
c = v.isnumeric()
d = v.isalpha()
e = v.isalnum()
f = v.isupper()
g = v.islower()
h = v.capitalize()
print('O tipo primitivo desse valor é: {}, tem espaços? {}, Numérico? {}, Alfabético? {}, Alfanumérico? {}, Maiusculas? {}, Minusculas? {}, Capitalizado? {}'.format(a, b, c, d, e, f, g, h))