print('Este exercício é sobre manipulação de textos: ')
nome = input('Digite seu nome completo: ')
fatiado = nome.split()
ultimo = len(fatiado)
print(ultimo)
print('Primeiro nome é: {}\nSegundo nome é: {}'.format(fatiado[0], fatiado[ultimo]))